### ISSUE TITLE
Can't call aether::det() directly.

### ISSUE THREAD

**Issue by chaosink** [aekul/aether#3]
```
aether::variable<0> u0;
aether::variable<1> u1;
auto r = sqrt(aether::one - sq(u0));
auto phi = two * get_pi() * u1;
auto x = r * cos(phi);
auto x_jac = aether::jacobian(x); // OK
// auto x_det = aether::det(x); // Error
auto x_det = abs(rcp(make_expr(determinant_tag, x_jac))); // OK
```

https://github.com/aekul/aether/blob/67039804f40f69187809792a148eef3e8b8209e4/Eval.h#L391-L394

**Comment by aekul** [comment]
Thanks for reporting this. It should be fixed by https://github.com/aekul/aether/commit/2e89cf4616add3c978965f907f8acf467b6e228e.

Also, `make_expr()` is not intended to be called directly (I plan to make it non-user accessible: https://github.com/aekul/aether/issues/5). In the meantime, if you do find you need to use it, then you've probably found a bug somewhere so feel free to create another issue.
